name: theater_vr_player
description: Immersive VR Theater Video Player for Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Video playback
  video_player: ^2.8.6
  chewie: ^1.8.5

  # VR / Panorama

  # UI & Animation
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  glass_kit: ^3.0.0
  blur: ^3.1.0

  # State Management
  provider: ^6.1.2
  
  # Utilities
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  wakelock_plus: ^1.2.8
  sensors_plus: ^5.0.1
  device_info_plus: ^10.1.2
  permission_handler: ^11.3.1
  
  # Icons & Fonts
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  file_picker: ^10.3.10
  vr_player: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#050810"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
#  fonts:
#    - family: Cinzel
#      fonts:
#        - asset: assets/fonts/Cinzel-Regular.ttf
#        - asset: assets/fonts/Cinzel-Bold.ttf
#          weight: 700
#    - family: Raleway
#      fonts:
#        - asset: assets/fonts/Raleway-Light.ttf
#          weight: 300
#        - asset: assets/fonts/Raleway-Regular.ttf
#        - asset: assets/fonts/Raleway-SemiBold.ttf
#          weight: 600
  assets:
    - assets/icons/
